version: '3.3'

services:
  nginx:
    image: download/nginx:latest
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/repo
     
      # My upload directory on my server
      - /home/mtai/upload:/host_upload_directory
    ports:
      - "17500:80"
